Repository nextcloud/suspicious_login, pull requests merged in 2019-08, with the labels that each got.

#137 Release v2.0.0
  CHANGELOG.md
Labels: 3. to review

#102 Use the nextcloud-initial-state package to access the API
  package-lock.json
  package.json
  src/main-settings.js
Labels: 3. to review, enhancement, technical debt

#97 Handle deserialization errors better
  lib/Service/EstimatorService.php
  lib/Service/ModelPersistenceService.php
Labels: 3. to review, bug

#139 Move to events
  lib/AppInfo/BootstrapSingleton.php
  lib/Event/SuspiciousLoginEvent.php
  lib/Listener/LoginNotificationListener.php
  lib/Service/LoginClassifier.php
Labels: 3. to review

#143 Use the correct namespaces
  lib/AppInfo/BootstrapSingleton.php
  lib/Listener/LoginNotificationListener.php
Labels: 3. to review, bug

#142 Also send a mail on a suspicious login event
  lib/AppInfo/BootstrapSingleton.php
  lib/Listener/LoginMailListener.php
Labels: 3. to review
