Repository nextcloud/suspicious_login, pull requests merged in 2019-10, with the labels that each got.

#164 Use official @nextcloud package
  package-lock.json
  package.json
  src/main-settings.js
Labels: 3. to review, technical debt

#168 Sorted issue with PostgreSQL
  lib/Service/ETLService.php
Labels: 2. developing, bug

#182 Always collect token login data
  lib/Listener/LoginListener.php
  tests/Unit/Listener/LoginListenerTest.php
Labels: 3. to review, bug
