Repository nextcloud/suspicious_login, pull requests merged in 2021-11, with the labels that each got.

#569 Downgrade to MariaDB 10.5 on CI
  .github/workflows/profile.yml
Labels: bug, 3. to review

#568 Smoke test the app (migrations) against some DBs
  .github/workflows/test.yml
Labels: 3. to review

#571 Update version on master
  appinfo/info.xml
Labels: 4. to release

#576 Fix missing import
  lib/Notifications/Notifier.php
Labels: bug, 3. to review
