Repository nextcloud/suspicious_login, pull requests merged in 2022-06, with the labels that each got.

#661 Remove Nextcloud 20 remnants
  .github/workflows/test.yml
Labels: 4. to release

#662 Only install LTS node and use `npm ci`
  .github/workflows/build.yml
Labels: 3. to review

#663 Allow PHP8.1
  .github/workflows/profile.yml
  .github/workflows/test.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 4. to release

#664 Drop Nextcloud 21 support
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#665 Migrate app.php to IBootstrap
  appinfo/app.php
  lib/AppInfo/Application.php
  lib/AppInfo/BootstrapSingleton.php
Labels: technical debt, 3. to review

#619 Make training jobs time insensitive
  lib/BackgroundJob/TrainJobIpV4.php
  lib/BackgroundJob/TrainJobIpV6.php
Labels: 3. to review
