Repository nextcloud/suspicious_login, pull requests merged in 2022-10, with the labels that each got.

#710 Bump league/flysystem from 2.0.8 to 2.5.0
  composer.json
  composer.lock
Labels: bug, 3. to review, backport-request

#709 [stable4.2] Add return type hints for occ commands
  lib/Command/ETL.php
  lib/Command/Optimize.php
  lib/Command/Predict.php
  lib/Command/Seed.php
  lib/Command/Train.php
Labels: bug, technical debt, 3. to review

#713 Do not test against server stable25
  .github/workflows/test.yml
Labels: technical debt, 3. to review

#715 [stable25] Do not test against server master
  .github/workflows/lint.yml
  .github/workflows/profile.yml
  .github/workflows/test.yml
Labels: 3. to review

#687 Update npm and node engines versions
  package.json
Labels: dependencies, backport-request

#724 Create command-compile.yml
  .github/workflows/command-compile.yml
Labels: 3. to review

#719 Compile JS
  .github/workflows/build.yml
  .github/workflows/node.yml
  .gitignore
  .l10nignore
  js/settings.js
  js/settings.js.LICENSE.txt
  js/settings.js.map
Labels: backport-request

#708 [stable25] Add return type hints for occ commands
  lib/Command/ETL.php
  lib/Command/Optimize.php
  lib/Command/Predict.php
  lib/Command/Seed.php
  lib/Command/Train.php
Labels: bug, technical debt, 3. to review
