Repository nextcloud/suspicious_login, pull requests merged in 2024-09, with the labels that each got.

#929 Migrate reuse to toml format
  .reuse/dep5
  REUSE.toml
Labels: technical debt, 4. to release

#914 chore: Update and replace workflows
  .github/workflows/command-compile.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/profile.yml
  .github/workflows/reuse.yml
  .github/workflows/test.yml
Labels: 3. to review

#931 fix: Replace deprecated ILogger with Psr\Log\LoggerInterface
  lib/BackgroundJob/TrainJobIpV4.php
  lib/BackgroundJob/TrainJobIpV6.php
  lib/Listener/LoginMailListener.php
  lib/Listener/LoginNotificationListener.php
  lib/Service/ETLService.php
  lib/Service/EstimatorService.php
  lib/Service/LoginClassifier.php
  lib/Service/ModelStore.php
  tests/Unit/Service/LoginClassifierTest.php
Labels: 3. to review

#927 [stable30] Fix npm audit
  js/settings.js
  js/settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#924 [master] Fix npm audit
  js/settings.js
  js/settings.js.license
  js/settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#932 ci: Only run renovate for 28 or newer
  renovate.json
Labels: 3. to review

#928 feat!: replace charts in admin settings with ocs stats api
  .babelrc.js
  .github/workflows/command-compile.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  REUSE.toml
  appinfo/info.xml
  js/settings.js
  js/settings.js.license
  js/settings.js.map
  krankerl.toml
  lib/Controller/StatisticsController.php
  lib/Service/StatisticsService.php
  lib/Settings/AdminSettings.php
  package-lock.json
  package.json
  renovate.json
  src/WebpackSPDXPlugin.js
  src/components/AdminSettings.vue
  src/components/ModelPerformance.vue
  src/components/ModelPerformanceChart.vue
  src/main-settings.js
  src/mixins/Nextcloud.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
  src/webpack.test.js
  tests/Unit/Service/StatisticsServiceTest.php
  tests/Unit/Settings/AdminSettingsTest.php
Labels: enhancement, 3. to review, 2. developing

#875 fix(LoginClassifier): Adjust log levels / reduce logging noise
  lib/Service/LoginClassifier.php
Labels: bug, 3. to review, backport-request, feedback-requested
