Repository nextcloud/suspicious_login, pull requests merged in 2024-02, with the labels that each got.

#838 fix(32bit): drop darsyn/ip dependency
  composer.json
  composer.lock
  lib/Service/IpV6Strategy.php
Labels: bug, technical debt, 3. to review, backport-request

#810 fix #745 ValueError: random_int(): Argument #1 ($min) must be less than or equal to argument #2 ($max)
  lib/Service/NegativeSampleGenerator.php
  tests/Unit/Service/NegativeSampleGeneratorTest.php
Labels: bug, 3. to review

#846 docs(README): Clarify older versions, app store, releases access
  README.md
Labels: enhancement, 3. to review

#852 ci: Profile with v6 addresses too
  .github/workflows/profile.yml
Labels: 3. to review, backport-request

#853 [stable26] ci: Profile with v6 addresses too
  .github/workflows/profile.yml
Labels: 3. to review, backport-request

#857 [stable28] ci: Profile with v6 addresses too
  .github/workflows/profile.yml
Labels: 3. to review

#858 [stable27] ci: Profile with v6 addresses too
  .github/workflows/profile.yml
Labels: 4. to release

#839 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies
