Repository nextcloud/suspicious_login, pull requests merged in 2024-08, with the labels that each got.

#898 chore: move php-cs-fixer to vendor-bin
  .github/workflows/lint.yml
  .gitignore
  .php-cs-fixer.dist.php
  .reuse/dep5
  composer.json
  composer.lock
  lib/BackgroundJob/ETLJob.php
  lib/BackgroundJob/TrainJobIpV4.php
  lib/BackgroundJob/TrainJobIpV6.php
  lib/Command/Seed.php
  lib/Command/Train.php
  lib/Db/LoginAddressAggregatedSeeder.php
  lib/Listener/LoginListener.php
  lib/Listener/LoginMailListener.php
  lib/Listener/LoginNotificationListener.php
  lib/Migration/Version0Date20181127130604.php
  lib/Migration/Version0Date20181213090142.php
  lib/Migration/Version0Date20181214080456.php
  lib/Migration/Version0Date20181214083108.php
  lib/Migration/Version0Date20181214103754.php
  lib/Migration/Version0Date20190115134303.php
  lib/Migration/Version0Date20190121184304.php
  lib/Migration/Version0Date20190123142603.php
  lib/Migration/Version2Date20190906100917.php
  lib/Migration/Version2Date20190913144908.php
  lib/Migration/Version4002Date20220922094803.php
  lib/Migration/Version4002Date20220922094804.php
  lib/Notifications/Notifier.php
  lib/Service/AdminService.php
  lib/Service/CollectedData.php
  lib/Service/DataLoader.php
  lib/Service/ETLService.php
  lib/Service/EstimatorService.php
  lib/Service/LoginClassifier.php
  lib/Service/MLP/Config.php
  lib/Service/MLP/OptimizerService.php
  lib/Service/MLP/Trainer.php
  lib/Service/ModelStore.php
  lib/Service/NegativeSampleGenerator.php
  lib/Service/Statistics/AppStatistics.php
  lib/Service/Statistics/TrainingDataStatistics.php
  lib/Service/TrainService.php
  lib/Service/TrainingDataConfig.php
  lib/Service/TrainingDataSet.php
  lib/Service/TrainingResult.php
  lib/Task/TrainTask.php
  vendor-bin/php-cs-fixer/composer.json
  vendor-bin/php-cs-fixer/composer.lock
Labels: technical debt, 3. to review

#884 [master] Fix npm audit
  js/settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#901 chore: move composer-bin-plugin to prod dependencies
  composer.json
  composer.lock
  vendor-bin/php-cs-fixer/composer.lock
Labels: 3. to review

#906 fix(php): Make OptimizerService::optimize nullalble param required
  lib/Service/MLP/OptimizerService.php
Labels: bug, technical debt, 3. to review, backport-request

#890 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#912 fix: inverted logo in notification
  lib/Notifications/Notifier.php
Labels: 4. to release, backport-request
