Repository nextcloud/suspicious_login, pull requests merged in 2024-07, with the labels that each got.

#882 Add npm audit fix job
  .github/workflows/npm-audit-fix.yml
Labels: technical debt, 3. to review

#883 [stable29] Fix npm audit
  js/settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#886 [stable28] Fix npm audit
  js/settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#885 [stable27] Fix npm audit
  js/settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#888 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#897 feat: Improved email and notification text
  lib/Listener/LoginMailListener.php
  lib/Notifications/Notifier.php
Labels: enhancement, 3. to review
