Repository nextcloud/suspicious_login, pull requests merged in 2025-07, with the labels that each got.

#1008 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1010 fix(php): suppress notice of JsonSerializable::jsonSerialize
  lib/Db/Model.php
  lib/Service/Statistics/AppStatistics.php
  lib/Service/Statistics/TrainingDataStatistics.php
  lib/Service/TrainingDataConfig.php
Labels: bug, 3. to review

#1015 [stable31] fix(deps): bump amphp/parallel to v1.4.4. for PHP8.4 compatibility
  composer.lock
Labels: bug, 4. to release
