Repository nextcloud/suspicious_login, pull requests merged in 2025-01, with the labels that each got.

#958 fix(NegativeSampleGenerator): Prevent duplicate user IDs when getting unique IPs
  lib/Service/NegativeSampleGenerator.php
  tests/Unit/Service/NegativeSampleGeneratorTest.php
Labels: bug, 4. to release, feedback-requested

#956 fix(deps): Bump symfony/process
  composer.lock
Labels: 3. to review, security, backport-request

#967 [stable30] fix(deps): Bump symfony/process
  composer.lock
Labels: 3. to review

#968 [stable29] fix(deps): Bump symfony/process
  composer.lock
Labels: 3. to review

#970 fix(deps): Make psr/log:3 compatible by rubix upgrade
  appinfo/info.xml
  composer.json
  composer.lock
  lib/BackgroundJob/TrainIpV4OnceJob.php
  lib/BackgroundJob/TrainIpV6OnceJob.php
  lib/Migration/Version9000Date20250114095826.php
  lib/Service/ModelStore.php
  lib/Service/TrainingResult.php
Labels: 4. to release

#969 [stable30] fix(NegativeSampleGenerator): Prevent duplicate user IDs when getting…
  lib/Service/NegativeSampleGenerator.php
  tests/Unit/Service/NegativeSampleGeneratorTest.php
Labels: bug, 3. to review
