Repository nextcloud/suspicious_login, pull requests merged in 2025-04, with the labels that each got.

#982 test: Set PHPUNIT_RUN env var
  tests/bootstrap.php
Labels: 3. to review

#979 fix: try to avoid memory exhaustion
  lib/Db/LoginAddressAggregatedMapper.php
  lib/Service/DataLoader.php
Labels: bug, 4. to release, backport-request

#981 fix(deps): Update rubix/ml to v2.5
  composer.json
  composer.lock
Labels: 4. to release, dependencies

#976 fix: exclude vendor-bin from release artifacts
  .nextcloudignore
Labels: 3. to review, backport-request
